<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Water</name>
   <tag></tag>
   <elementGuidId>18ad8e0a-eb26-4801-b432-6005b9406585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ag-cell.ag-cell-not-inline-editing.ag-cell-normal-height.ag-cell-value.ag-cell-focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div/div/div[3]/div/div/div[2]/div/div[3]/div/div[2]/div[3]/div/div[2]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.ag-row-even > div:nth-child(2) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>344394c6-e63d-4c87-b117-8cd44e47fa59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>9c2ea1e9-e433-4d7b-b0d3-bf9be8d305f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>col-id</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>ba5b26dd-dae3-4c6b-8b05-c1fc10a23590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3578f227-18dc-4a7d-b536-3d2da9557909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-cell ag-cell-not-inline-editing ag-cell-normal-height ag-cell-value ag-cell-focus</value>
      <webElementGuid>8fe2844b-e062-46dc-9565-dc16ec9a8251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>dc390e09-1faa-4c41-9101-482fcca5805a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Water</value>
      <webElementGuid>6f331694-1332-444b-a625-389f1a05a846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;m_89ab340 mantine-AppShell-root&quot;]/main[@class=&quot;m_8983817 mantine-AppShell-main&quot;]/div[1]/div[1]/div[1]/div[3]/div[@class=&quot;ag-theme-quartz wrapper-table&quot;]/div[@class=&quot;DataGrid-module__container__lamyv&quot;]/div[@class=&quot;DataGrid-module__grid__LtRZB&quot;]/div[@class=&quot;ag-theme-params-2 ag-theme-buttonStyle-1 ag-theme-columnDropStyle-2 ag-theme-checkboxStyle-3 ag-theme-iconSet-4 ag-theme-tabStyle-5 ag-theme-inputStyle-6 ag-theme-columnDropStyle-2&quot;]/div[@class=&quot;ag-root-wrapper ag-ltr ag-layout-normal&quot;]/div[@class=&quot;ag-root-wrapper-body ag-focus-managed ag-layout-normal&quot;]/div[@class=&quot;ag-root ag-unselectable ag-layout-normal ag-body-horizontal-content-no-gap ag-body-vertical-content-no-gap&quot;]/div[@class=&quot;ag-body ag-layout-normal&quot;]/div[@class=&quot;ag-body-viewport ag-row-animation ag-layout-normal ag-has-focus&quot;]/div[@class=&quot;ag-viewport ag-center-cols-viewport&quot;]/div[@class=&quot;ag-center-cols-container&quot;]/div[@class=&quot;ag-row-even ag-row ag-row-level-0 ag-row-position-absolute ag-row-first ag-row-not-inline-editing ag-row-focus ag-row-hover&quot;]/div[@class=&quot;ag-cell ag-cell-not-inline-editing ag-cell-normal-height ag-cell-value ag-cell-focus&quot;]</value>
      <webElementGuid>a01d5afd-ebee-4cb7-8f26-948ee2282278</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div/div[3]/div/div/div[2]/div/div[3]/div/div[2]/div[3]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>43172489-588d-4dee-b821-10a930a27ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T-RD322'])[1]/following::div[1]</value>
      <webElementGuid>04eb1843-b73c-4612-8de9-e86db635b729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material Group'])[1]/following::div[15]</value>
      <webElementGuid>094f4408-95a4-4f68-a8af-2d4f8d214c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C44DF104-9C45-46C3-95B9-9565FE6BBAB7'])[1]/preceding::div[6]</value>
      <webElementGuid>e158337f-7b5b-4032-8ec6-d51786802165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T-RI520'])[1]/preceding::div[7]</value>
      <webElementGuid>bfa2ad78-a321-4fa0-8a83-16bd4f1df336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Water']/parent::*</value>
      <webElementGuid>b36831bc-5f76-42ed-b068-06ce475df1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>a572069b-0f0d-4561-baae-562309152608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Water' or . = 'Water')]</value>
      <webElementGuid>ad8451d4-1481-4a7a-b032-55dab942aa73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
