<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Field_mantine-w5dl24h4o</name>
   <tag></tag>
   <elementGuidId>3928ddec-f618-425b-a302-15bcbdfc94e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-w5dl24h4o</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-w5dl24h4o']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Select field&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96acf61c-12fc-4357-9a45-0fc75cfbfc57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m_8fb7ebe7 mantine-Input-input mantine-Select-input</value>
      <webElementGuid>e2375128-2033-47de-b9cb-3dc79292d6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-variant</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>29603643-b4cf-48d2-b70a-0090a5ba2ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select field</value>
      <webElementGuid>4e3a374d-96f7-4cae-b419-9c5a20260ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>c2d33ee2-cc1a-4d98-8c92-4ddaed4582cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>efc95b74-0864-43a3-8751-50af89af3d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f332f74b-275e-4c50-9f9d-010a5d142671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-w5dl24h4o</value>
      <webElementGuid>a4578bfd-3425-4adb-b6fe-2aef1d439b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mantine-tzat4dot5</value>
      <webElementGuid>e8ea60c3-3f7d-4fbf-8463-fab110464417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a3ae6433-3679-4dd6-b895-1a1232159858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mantine-stop-propagation</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a2fbe3ad-88fa-41e2-a82b-7111e3182282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-w5dl24h4o&quot;)</value>
      <webElementGuid>70783192-92dd-4656-a439-afe6f52ebfc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-w5dl24h4o']</value>
      <webElementGuid>1d4dc1b0-b57a-4a37-b27f-b87c3d00ffa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-kpbs8zyhp-dropdown']/div/div[2]/div/input</value>
      <webElementGuid>46b1be03-0f22-41fa-9dc0-827be1c760f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/div[2]/div/input</value>
      <webElementGuid>a5010886-fce2-4510-9e0d-30baf36a5c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Select field' and @id = 'mantine-w5dl24h4o']</value>
      <webElementGuid>26085ee2-4a30-4c49-9c77-a53e5a4425ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
