<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login_Input_Password</name>
   <tag></tag>
   <elementGuidId>50858e86-cdd3-4ab9-91a1-a34324ec4ef3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/div/form/div/div[2]/div/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mantine-rckv8ptad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Your password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>297347af-b8a7-4072-8a4d-a66b752e6907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-with-left-section</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6346c77e-20b9-49ed-94aa-aa645130b935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m_f2d85dd2 mantine-PasswordInput-innerInput</value>
      <webElementGuid>a4c727d2-a1f9-4c71-826d-bd9d139ca411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-rckv8ptad</value>
      <webElementGuid>98d21e32-4544-4b54-a720-4ad18821e6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your password</value>
      <webElementGuid>5d7268da-b82d-42b0-8ba6-73ded4fc884c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3f8d88d3-7213-455c-9a30-dc94141485f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b46f10c9-0bec-41c1-b910-dff0a06d8823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e25c78d9-1461-4512-bdff-0e88d3f71762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8ad7ea1d-94c0-4ddd-9f9d-02223e138912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-rckv8ptad&quot;)</value>
      <webElementGuid>20b4759b-0a18-4a24-81fd-c6166dd59879</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-rckv8ptad']</value>
      <webElementGuid>ff7c5cc5-ea51-4e42-bbec-6694b42b1121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/form/div/div[2]/div/div[2]/input</value>
      <webElementGuid>68175440-9516-42ff-9537-35c8acbd47b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>6c2d80a5-d92f-4bf6-9204-e8a2824db1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mantine-rckv8ptad' and @placeholder = 'Your password' and @type = 'password' and @name = 'password']</value>
      <webElementGuid>a044f330-f205-4996-9315-ff63128318e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
